openapi: 3.0.0
info:
  version: 0.1.0
  title: Natural Language Understanding API
  description: "Vonage Natural Language Understanding API allows you to build, store, and use model's for intent \nand entity detection from user utterances.\n"
  contact:
    name: Nexmo
    url: 'https://developer.nexmo.com/'
    email: devrel@nexmo.com
servers:
  - url: 'https://api.nexmo.com/v0.1/athena'
paths:
  "/entities/{entity_iud}/values/{value_id}/synonyms":
    get:
      operationId: get_synonyms
      tags:
        - synonym
      summary: List synonyms for an entity value
      parameters:
        - $ref: "#/components/parameters/page_size"
        - $ref: "#/components/parameters/cursor"
        - $ref: "#/components/parameters/order"
      responses:
        "200":



components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    page_size:
      name: page_size
      in: query
      description: The number of results returned per page.   The default value is `10`. The maximum value is `100`.
      schema:
        type: integer
        default: 10
        maximum: 100
      required: false
    order:
      name: order
      in: query
      description: Show the most (`desc`) / least (`asc`) recently created entries first
      schema:
        type: string
        default: asc
        enum:
          - asc
          - desc
      required: false
    cursor:
      name: cursor
      in: query
      description: |
        The cursor to start returning results from.

        You are not expected to provide this manually, but to follow the url provided in `_links.next.href` in the response which contains a `cursor` value
      schema:
        type: string
      required: false
    synonym_id:
      name: synonym_id
      in: path
      description: The Id of the synonym
      schema:
        type: string
      required: true
  schemas:    
    synonym:
      properties:
        _links:
          type: object
          properties:
            first:
              type: object
              properties:
                href:
                  type: string
                  example: 'https://api.nexmo.com/v0.1/athena/entities/ENT-92a44c64-7e4e-485f-a0c4-1f2adfc44625/values/VAL-92a44c64-7e4e-485f-a0c4-1f2adfc44625?order=desc&page_size=10'
            self:
              type: object
              properties:
                href:
                  type: string
                  example: 'https://api.nexmo.com/v0.1/athena/entities/ENT-92a44c64-7e4e-485f-a0c4-1f2adfc44625/values/VAL-92a44c64-7e4e-485f-a0c4-1f2adfc44625?order=desc&page_size=10&cursor=88b395c167da4d94e929705cbd63b82973771e7d390d274a58e301386d5762600a3ffd799bfb3fc5190c5a0d124cdd0fc72fe6e450506b18e4e2edf9fe84c7a0'
            next:
              type: object
              properties:
                href:
                  type: string
                  example: 'https://api.nexmo.com/v0.1/athena/entities/ENT-92a44c64-7e4e-485f-a0c4-1f2adfc44625/values/VAL-92a44c64-7e4e-485f-a0c4-1f2adfc44625?order=desc&page_size=10&cursor=88b395c167da4d94e929705cbd63b829a650e69a39197bfd4c949f4243f60dc4babb696afa404d2f44e7775e32b967f2a1a0bb8fb259c0999ba5a4e501eaab55'
            prev:
              type: object
              properties:
                href:
                  type: string
                  example: 'https://api.nexmo.com/v0.1/athena/entities/ENT-92a44c64-7e4e-485f-a0c4-1f2adfc44625/values/VAL-92a44c64-7e4e-485f-a0c4-1f2adfc44625?order=desc&page_size=10&cursor=069626a3de11d2ec900dff5042197bd75f1ce41dafc3f2b2481eb9151086e59aae9dba3e3a8858dc355232d499c310fbfbec43923ff657c0de8d49ffed9f7edb'
        id:
          type: string
          example: SYN-afe887d8-d587-4280-9aae-dfa4c9227d5e
        value:
          type: string
          example: mint