---
openapi: 3.0.0
servers:
  - url: 'https://api.nexmo.com/v2/ni'
security:
  - basicAuth: []
  - bearerAuth: []
info:
  title: Number Insight API (v2)
  version: 0.0.1
  description: Number Insight v2 is designed to give fraud scores for Application Integrations.
  contact:
    name: Vonage DevRel
    email: devrel@vonage.com
    url: 'https://developer.vonage.com/'
  termsOfService: 'https://www.vonage.com/terms-of-use'
  license:
    name: The MIT License (MIT)
    url: 'https://opensource.org/licenses/MIT'
externalDocs:
  url: 'https://developer.vonage.com/number-insight/overview'
  x-sha1: 081f6d985e2e4a75586da1654fde880a96885405
paths:
  /:
    post:
      operationId: getNumberInsightBasic
      summary: Number Insight v2 default endpoint
      description: |
        This is the default endpoint to make requests for Insight data.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: Accepted value is “phone” when a phone number is provided to receive insight.
                  enum:
                    - phone
                  example: 'phone'
                phone:
                  type: string
                  description: A single phone number that you need insight about in national or international format.".
                  example: '003544569382'
                # email:
                #   type: string
                #   description: Email address. Required if type = "email".
                #   example: 'jim@doe.com'
                # ip:
                #   type: string
                #   description: Ip address. Required if type = "ip"
                #   example: '202.453.231.34'
                insights:
                  type: array
                  enum:
                    - 'fraud_score'
                  example: ['fraud_score']
                  items:
                    type: string
              required:
                - phone
                - type
                - insights
        description: ''
      responses:
        '200':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: string
                    example: 'aaaaaaaa-bbbb-cccc-dddd-0123456789ab'
                  type:
                    type: string
                    example: phone
                  phone:
                    type: object
                    properties:
                      phone:
                        type: string
                        example: '16197363066'
                      carrier:
                        type: string
                        example: 'Google (Grand Central) - SVR'
                      phone_type:
                        type: string
                        example: 'VOIP'
                  fraud_score:
                    type: object
                    properties:
                      risk_score:
                        type: string
                        example: '70'
                      risk_recommendation:
                        type: string
                        example: 'block'
                      label:
                        type: string
                        example: high
        '400':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: "Your request parameters didn't validate."
                  detail:
                    type: string
                    example: 'Found errors validating 1 of your submitted parameters.'
                  instance:
                    type: string
                    example: 'a00a6d15-27db-49e7-802c-4162ebd92e61'
                  type:
                    type: string
                    example: 'https://developer.vonage.com/api-errors'
                  invalid_parameters:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: 'type'
                        reason:
                          type: string
                          example: 'must not be null'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: 'Invalid params'
                  detail:
                    type: string
                    example: 'The value of one or more parameters is invalid'
                  instance:
                    type: string
                    example: '06032957-99ce-41ee-978b-9a390cd5a89b'
                  type:
                    type: string
                    example: 'https://www.nexmo.com/messages/Errors#InvalidParams'
                  invalid_parameters:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          example: 'value'
                        reason:
                          type: string
                          example: 'invalid value'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: 'Internal error'
                  detail:
                    type: string
                    example: 'There was an error processing your request in our platform'
                  instance:
                    type: string
                    example: '06032957-99ce-41ee-978b-9a390cd5a89b'
                  type:
                    type: string
                    example: 'https://www.nexmo.com/messages/Errors#InvalidParams'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: HTTP auth can be used for syncronous calls, for asyncronous calls and call backs use JWT authentication

    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
