---
openapi: 3.0.0
servers:
  - url: 'https://api.nexmo.com/v2/ni'
info:
  title: Number Insight API (v2)
  version: 0.0.1
  description: Number Insight v2 is designed to give fraud scores for Application Integrations.
  contact:
    name: Vonage DevRel
    email: devrel@vonage.com
    url: 'https://developer.vonage.com/'
  termsOfService: 'https://www.vonage.com/terms-of-use'
  license:
    name: The MIT License (MIT)
    url: 'https://opensource.org/licenses/MIT'
externalDocs:
  url: 'https://developer.nexmo.com/api/number-insight'
  x-sha1: 081f6d985e2e4a75586da1654fde880a96885405
paths:
  /:
    post:
      operationId: getNumberInsightBasic
      summary: Number Insight v2 default endpoint
      description: |
        This is the default endpoint to make requests for Insight data.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - phone
                    - email
                    - ip
                  example: 'phone'
                phone:
                  type: string
                  description: Phone number. Required if type = "phone".
                  example: '003544569382'
                email:
                  type: string
                  description: Email address. Required if type = "email".
                  example: 'jim@doe.com'
                ip:
                  type: string
                  description: Ip address. Required if type = "ip"
                  example: '202.453.231.34'
                insights:
                  type: string
                  enum:
                    - fraud_score
                  example: 'fraud_score'
              required:
                - type
                - insights
        description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: string
                  type:
                    type: string
                  phone:
                    type: object
                    properties:
                      phone:
                        type: string
                      carrier:
                        type: string
                      phone_type:
                        type: string
                  fraud_score:
                    type: object
                    properties:
                      risk_score:
                        type: string
                      risk_recommendation:
                        type: string
                      label:
                        type: string
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    request_id: aaaaaaaa-bbbb-cccc-dddd-0123456789ab
                    type: phone
                    phone:
                      phone: '16197363066'
                      carrier: Google (Grand Central) - SVR
                      type: VOIP
                    fraud_score:
                      risk_score: '52'
                      label: very low/low/medium-low/medium/high/very high
                      risk_recommendation: allow/flag/block
                properties:
                  request_id:
                    type: string
                  type:
                    type: string
                  phone:
                    type: object
                    properties:
                      phone:
                        type: string
                      carrier:
                        type: string
                      type:
                        type: string
                  fraud_score:
                    type: object
                    properties:
                      risk_score:
                        type: string
                      label:
                        type: string
                      risk_recommendation:
                        type: string
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  detail:
                    type: string
                  instance:
                    type: string
                  type:
                    type: string
                  invalid_parameters:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        reason:
                          type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  detail:
                    type: string
                  instance:
                    type: string
                  type:
                    type: string

