openapi: 3.0.0
x-stoplight:
  id: hfgkh9ei1nqdg
servers:
  - url: 'https://api.nexmo.com/v2/ni'
info:
  title: Number Insight API (v2)
  version: 0.0.1
  description: Number Insight v2 is designed to give fraud scores for Application Integrations.
  contact:
    name: Vonage DevRel
    email: devrel@vonage.com
    url: 'https://developer.vonage.com/'
  termsOfService: 'https://www.vonage.com/terms-of-use'
  license:
    name: The MIT License (MIT)
    url: 'https://opensource.org/licenses/MIT'
externalDocs:
  url: 'https://developer.nexmo.com/api/number-insight'
  x-sha1: 081f6d985e2e4a75586da1654fde880a96885405
security:
  - apiKey: []
    apiSecret: []
paths:
  /:
    post:
      operationId: getNumberInsightBasic
      summary: Number Insight v2 default endpoint
      description: |
        This is the default endpoint to make requests for Insight data.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  type: phone
                  phone: '16197363066'
                  insights: fraud_score
              properties:
                type:
                  type: string
                  enum:
                    - phone
                    - email
                    - ip
                phone:
                  type: string
                  description: Phone number. Required if type = "phone".
                email:
                  type: string
                  description: Email address. Required if type = "email".
                ip:
                  type: string
                  description: Ip address. Required if type = "ip"
                insights:
                  type: string
                  enum:
                    - fraud_score
              required:
                - type
                - insights
            examples:
              example-1:
                value:
                  type: phone
                  phone: '16197363066'
                  insights: fraud_score
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: string
                  type:
                    type: string
                  phone:
                    type: object
                    properties:
                      phone:
                        type: string
                      carrier:
                        type: string
                      phone_type:
                        type: string
                  fraud_score:
                    type: object
                    properties:
                      risk_score:
                        type: string
                      risk_recommendation:
                        type: string
                      label:
                        type: string
                x-examples:
                  example-1:
                    request_id: aaaaaaaa-bbbb-cccc-dddd-0123456789ab
                    type: phone
                    phone:
                      phone: '15555555555'
                      carrier: ''
                      phone_type: INVALID
                    fraud_score:
                      risk_score: '100'
                      risk_recommendation: block
                      label: high
              examples:
                example-1:
                  value:
                    request_id: aaaaaaaa-bbbb-cccc-dddd-0123456789ab
                    type: phone
                    phone:
                      phone: '15555555555'
                      carrier: ''
                      phone_type: INVALID
                    fraud_score:
                      risk_score: '100'
                      risk_recommendation: block
                      label: high
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    request_id: aaaaaaaa-bbbb-cccc-dddd-0123456789ab
                    type: phone
                    phone:
                      phone: '16197363066'
                      carrier: Google (Grand Central) - SVR
                      type: VOIP
                    fraud_score:
                      risk_score: '52'
                      label: very low/low/medium-low/medium/high/very high
                      risk_recommendation: allow/flag/block
                properties:
                  request_id:
                    type: string
                  type:
                    type: string
                  phone:
                    type: object
                    properties:
                      phone:
                        type: string
                      carrier:
                        type: string
                      type:
                        type: string
                  fraud_score:
                    type: object
                    properties:
                      risk_score:
                        type: string
                      label:
                        type: string
                      risk_recommendation:
                        type: string
              examples:
                example-1:
                  value:
                    request_id: aaaaaaaa-bbbb-cccc-dddd-0123456789ab
                    type: phone
                    phone:
                      phone: '16197363066'
                      carrier: Google (Grand Central) - SVR
                      type: VOIP
                    fraud_score:
                      risk_score: '52'
                      label: very low/low/medium-low/medium/high/very high
                      risk_recommendation: allow/flag/block
        '422':
          description: Unprocessable Entity (WebDAV)
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  detail:
                    type: string
                  instance:
                    type: string
                  type:
                    type: string
                  invalid_parameters:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        reason:
                          type: string
                x-examples:
                  example-1:
                    title: Invalid params
                    detail: The value of one or more parameters is invalid
                    instance: 06032957-99ce-41ee-978b-9a390cd5a89b
                    type: 'https://www.nexmo.com/messages/Errors#InvalidParams'
                    invalid_parameters:
                      - name: value
                        reason: Invalid value
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                  detail:
                    type: string
                  instance:
                    type: string
                  type:
                    type: string
                x-examples:
                  example-1:
                    title: Internal error
                    detail: There was an error processing your request in our platform
                    instance: 06032957-99ce-41ee-978b-9a390cd5a89b
                    type: 'https://www.nexmo.com/messages/Errors#InvalidParams'
components:
  parameters: {}
  securitySchemes:
    apiKey:
      name: API Key
      type: apiKey
      in: query
    apiSecret:
      name: API Key
      type: apiKey
      in: query
