openapi: "3.0.1"
info:
  version: 0.3.6
  title: WhatsApp Manager API
  description: | 
    The WhatsApp Manager API enables customers to deploy a WhatsApp cluster and perform the OTP verfication. Profile information can also be submitted.
    
    Deployment States:

    `INITIALIZING` "The request has been accepted"
    
    `CREATING_CLUSTER` “Creating number”
    
    `CLUSTER_CREATED` “Number has been created”
    
    `CODE_SENT` “Code has been sent via preferred method”
    
    `WRONG_CODE` “Invalid code has been entered”
    
    `CODE_VERIFIED` “Correct code provided”
    
    `FINALIZING` “Finalising and activating number” 
    
    `READY` “Number is ready for live traffic”
    
    `ERROR` “Non recoverable errors”
    
    `DELETING` “Number is being deleted”
    
    `DELETED` “Number has been deleted”
  
  contact:
    name: Nexmo DevRel
    email: devrel@nexmo.com
    url: 'https://developer.nexmo.com/'
  x-label: Beta
servers:
  - url: https://api.nexmo.com/v0.1/whatsapp-manager
paths:
  /deployments:
    post:
      security:
        - bearerAuth: []
        - basicAuth: []
      summary: Provision WhatsApp deployment and trigger OTP.
      description: This is the first API request that you make. It will provision a WhatsApp cluster (`INITIALIZING` -> `CREATING_CLUSTER` -> `CLUSTER_CREATED` ) and once it is ready it will trigger the OTP call or SMS to the number specified (`CODE_SENT`). Once you receive the code use the verify api call to finish the process. Please note that the `pin` is only required in the request if you previously set one on your WhatsApp number.
      
      operationId: deployment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Deployment'
      responses:
        '202':
          description: Accepted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  deployment_id:
                    type: string
                    example: aaaaaaaa-bbbb-cccc-dddd-0123456789ab
          
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    
  /deployments/{deployment_id}:
    get:
      security:
        - bearerAuth: []
        - basicAuth: []
      summary: Get the status of a deployment.
      parameters:
        - in: path
          name: deployment_id
          required: true
          schema:
            type: string
            minimum: 1
          description: The Deployment ID
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: object
                properties:
                  deployment_id:
                    type: string
                    example: aaaaaaaa-bbbb-cccc-dddd-0123456789ab
                  country_code:
                    type: string
                    example: '44'
                  number:
                    type: string
                    example: '7877001122'
                  api_key:
                    type: string
                    example: aaa111
                  current_state:
                    type: object
                    properties:
                      state:
                        type: string
                        example: error
                        enum: 
                          - INITIALIZING
                          - CREATING_CLUSTER
                          - CLUSTER_CREATED
                          - CODE_SENT
                          - WRONG_CODE
                          - CODE_VERIFIED
                          - FINALIZING
                          - READY
                          - ERROR
                          - DELETING
                          - DELETED
                      description:
                        type: string
                        example: Invalid Vname certificate
          
        '404':
          description: Deploment not found.
          
  /deployments/{deployment_id}/resend-otp:
    post:
      security:
        - bearerAuth: []
        - basicAuth: []
      summary: Resend the OTP.
      description: If you do not receive the code in five minutes then you can request for it to be sent again.
      operationId: resend-otp
      parameters:
        - in: path
          name: deployment_id
          required: true
          schema:
            type: string
            minimum: 1
          description: The Deployment ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resend-OTP'
      responses:
        '201':
          description: No action needed, already verified.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: No action needed
                  vname:
                    type: string
                    example: your vname
          
        '202':
          description: Code sent.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Code sent
                  vname:
                    type: string
                    example: your vname
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
        '409':
          description: Conflict.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error2'
          
        '429':
          description: Too Many Requests.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error2'
          

  /deployments/{deployment_id}/verify:
    post:
      security:
        - bearerAuth: []
        - basicAuth: []
      summary: Verify the OTP code.
      description: When a code is successfully verifed, WhatsApp Manager will move the number from a `CODE_VERIFIED` state to a `FINALIZING` state where additional checks are made and it is assigned to your API Key. Once this is complete it will enter a `READY` state and the number is ready to use.
      operationId: verify
      parameters:
        - in: path
          name: deployment_id
          required: true
          schema:
            type: string
            minimum: 1
          description: The Deployment ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: '674639'
      responses:
        '200':
          description: Accepted.
          
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
        '429':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error2'

  /deployments/{deployment_id}/profiles:
    patch:
      security:
        - bearerAuth: []
        - basicAuth: []
      summary: Update WhatsApp Profile information.
      operationId: profiles
      parameters:
        - in: path
          name: deployment_id
          required: true
          schema:
            type: string
            minimum: 1
          description: The Deployment ID
      requestBody:
        description: Provision WhatsApp deployment and trigger OTP.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                about:
                  type: string
                  example: about your business
                  minLength: 1
                  maxLength: 139
                address:
                  type: string
                  example: your business address
                  minLength: 1
                  maxLength: 256
                description:
                  type: string
                  example: your business description
                  minLength: 1
                  maxLength: 256
                email:
                  type: string
                  example: your@business-email.com
                  minLength: 1
                  maxLength: 256
                veritcal:
                  type: string
                  enum:
                    - Automotive
                    - Beauty, Spa and Salon
                    - Clothing and Apparel
                    - Education
                    - Entertainment
                    - Event Planning and Service
                    - Finance and Banking
                    - Food and Grocery
                    - Public Service
                    - Hotel and Lodging
                    - Medical and Health
                    - Non-profit
                    - Professional Services
                    - Shopping and Retail
                    - Travel and Transportation
                    - Restaurant
                    - Other
                websites:
                  type: array
                  items:
                    type: string
                    example: https://your-website-1.com
                  minItems: 1
                  maxItems: 2
                
      responses:
        '200':
          description: OK.
          
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /deployments/{deployment_id}/profiles/photos:
    post:
      security:
        - bearerAuth: []
        - basicAuth: []
      summary: Upload a profile photo.
      operationId: profiles-photo
      parameters:
        - in: path
          name: deployment_id
          required: true
          schema:
            type: string
            minimum: 1
          description: The Deployment ID
      requestBody:
        description: URL pointing to a .png or .jpg. Image must be minimum 192px. max 640px x 640px. max 5MB.
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - profile_photo_url
              properties:
                profile_photo_url:
                  type: string
                  example: https://www.img.com/789
      responses:
        '201':
          description: Created.
          
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error2'


components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:
      type: http
      scheme: basic

  schemas:

    Deployment:
      required:
        - country_code
        - number
        - vname_certificate 
        - method
        - waba_id
      properties:
        country_code:
          type: string
          example: 44'
        number:
          type: string
          example: 7877001122'
        vname_certificate:
          type: string
          example: 'CnQKMAj669nb79e+AhIGiudfsishdfjZXN0IFFBIFBST0RLOFMgMlDHydLzBRpALFAvH9GvCS1FhrClT497rFKi9fKoi8ijMw1vj2Hv06f078XhABjT3LCVuUi1N2b9Xo3ka89yk31lejlksdjflsdf6hsIZZe5OBUxNjajx5yTaTE67uiunfsd'
        method:
          type: string
          enum:
            - sms
            - voice
        waba_id:
          type: string
          description: WABA ID of the WhatsApp Number
          example: '345676589250625'
        pin:
          type: string
          description: If you previously set a pin when creating a WhatsApp number you will need to specify it here.
          example: '123456'
    
    Resend-OTP:
      properties:
         method:
          type: string
          enum:
            - sms
            - voice
    
    Error:
      description: 'The error format is standardized to the 4xx/5xx range with a code and a human readable explanation.'
      required:
        - type
        - title
        - detail
        - instance
      properties:
        type:
          type: string
          example: 'https://www.nexmo.com/messages/Errors#InvalidParams'
        title:
          type: string
          example: 'Invalid Parameters'
        detail:
          type: string
          example: 'Your request parameters did not validate.'
        invalid_parameters:
          type: object
          properties:
            name:
              type: string
              example: vname_certificate
            reason:
              type: string
              example: is required parameter
        instance:
          type: string
          example: f94b4e56604e07e5e5ad5a7228618f81
    
    Error2:
      description: 'The error format is standardized to the 4xx/5xx range with a code and a human readable explanation.'
      required:
        - type
        - title
        - detail
        - instance
      properties:
        type:
          type: string
          example: 'https://www.nexmo.com/messages/Errors#InvalidParams'
        title:
          type: string
          example: 'Invalid Parameters'
        detail:
          type: string
          example: 'Your request parameters did not validate.'
        instance:
          type: string
          example: f94b4e56604e07e5e5ad5a7228618f81